// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMHwM2vEaMaEjObg6-mmIa22hr2TaJwhY',
    appId: '1:267281790888:web:638dfc5986f3cd76728f9d',
    messagingSenderId: '267281790888',
    projectId: 'aplikasifasum1',
    authDomain: 'aplikasifasum1.firebaseapp.com',
    databaseURL: 'https://aplikasifasum1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasifasum1.appspot.com',
    measurementId: 'G-FBK8FFYPTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNcEoQGO8Fbv0LoL4TWld5WPbCmHp3JMo',
    appId: '1:267281790888:android:16bf220792264f6c728f9d',
    messagingSenderId: '267281790888',
    projectId: 'aplikasifasum1',
    databaseURL: 'https://aplikasifasum1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasifasum1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhfB9ieOvfRGIik2Nbo3jxxbMHBIaCbLM',
    appId: '1:267281790888:ios:41ff1860f1e3a772728f9d',
    messagingSenderId: '267281790888',
    projectId: 'aplikasifasum1',
    databaseURL: 'https://aplikasifasum1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasifasum1.appspot.com',
    iosBundleId: 'com.example.aplikasiFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhfB9ieOvfRGIik2Nbo3jxxbMHBIaCbLM',
    appId: '1:267281790888:ios:41ff1860f1e3a772728f9d',
    messagingSenderId: '267281790888',
    projectId: 'aplikasifasum1',
    databaseURL: 'https://aplikasifasum1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasifasum1.appspot.com',
    iosBundleId: 'com.example.aplikasiFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMHwM2vEaMaEjObg6-mmIa22hr2TaJwhY',
    appId: '1:267281790888:web:57576f6be10e6ae6728f9d',
    messagingSenderId: '267281790888',
    projectId: 'aplikasifasum1',
    authDomain: 'aplikasifasum1.firebaseapp.com',
    databaseURL: 'https://aplikasifasum1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasifasum1.appspot.com',
    measurementId: 'G-9RW9YG9MCG',
  );
}
